version: '3.9'
services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - api
